logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
server:
  port: 8084
security.sessions: NEVER
spring.redis.host: localhost
eureka:
  instance:
    hostname: localhost
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure
  public.directory: /home/admdevlin/ArchivosFGN/public