logging.level.: 'INFO'
server:
  port: 8084
security.sessions: NEVER
eureka:
  instance:
    hostname: localhost
spring.redis.host: localhost
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: '{cipher}77773399b5878b5eebbfac49d96f10c819cd2f592d38793c8d7044853bc7d910'
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
spring.files:
  private.directory: D:/ArchivosFGN/secure/
  public.directory: D:/ArchivosFGN/public/