logging.level.: 'ERROR'
server:
  port: 8084
security.sessions: NEVER
eureka:
  instance:
    hostname: localhost
spring.redis.host: localhost
spring:
  datasource:
    url: jdbc:oracle:thin:@10.1.7.183:1521/portaldbdev
    username: system
    password: '{cipher}5545ea6212fd4db7ddcb23a8c18e31d242ce0abd6e01c0bafdd6ad8241c47fd6'
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
spring.files:
  private.directory: D:/ArchivosFGN/secure/
  public.directory: D:/ArchivosFGN/public/