security.sessions: NEVER
server:
  port: 8081
  ssl: 
    key-store: keystore.p12
    key-store-password: Mimojal263!.
    keyStoreType: PKCS12
    keyAlias: tomcat
logging.level.: INFO
spring:
  redis.host: localhost
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SUSI_CORE
    password: '{cipher}77773399b5878b5eebbfac49d96f10c819cd2f592d38793c8d7044853bc7d910'
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: d:/archivosFGN/lucene/indexes/
    generate-ddl: true
    hibernate.ddl-auto: update 
    show-sql: false
eureka:
  instance:
    securePortEnabled: true
    hostname: localhost
spring.files:
  private.directory: D:/ArchivosFGN/secure/
  public.directory: D:/ArchivosFGN/public/
  core.userPictures.directory: user-pictures/
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 10000
    strategy: THREAD