security.sessions: NEVER
logging.level.: ERROR
server:
  port: 8081
spring:
  redis.host: 192.168.12.9
  datasource:
    url: jdbc:oracle:thin:@192.168.12.7:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: /home/admdevlin/archivosFGN/lucene/indexes/
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
eureka:
  serviceUrl:
    default: http://192.168.12.9:8761/eureka/
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure/
  public.directory: /home/admdevlin/ArchivosFGN/public/
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 10000
    strategy: THREAD