logging.level.: WARN
security.sessions: NEVER
server:
  port: 8081
spring:
  redis.host: 192.168.12.9
  datasource:
    url: jdbc:oracle:thin:@192.168.12.7:1521:xe
    username: SUSI_CORE
    password: '{cipher}77773399b5878b5eebbfac49d96f10c819cd2f592d38793c8d7044853bc7d910'
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties.hibernate.search.default:
      directory_provider: filesystem
      indexBase: /home/admdevlin/archivosFGN/lucene/indexes/
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.12.9:8761/eureka/
  instance:
    preferIpAddress: true
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure/
  public.directory: /home/admdevlin/ArchivosFGN/public/
  core.userPictures.directory: user-pictures/
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 10000
    strategy: THREAD