security.sessions: NEVER
logging.level.: WARN
server.port: 8083
spring:
  redis.host: 192.168.12.9
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.12.9:8761/eureka/
  instance:
    preferIpAddress: true
