logging.level.: WARN
security:
  sessions: ALWAYS
server:
  port: 8082
  
  ssl:
    enabled: true
    key-store: classpath:keystore-susi.p12
    key-store-password: Mimojal263!.
    keyStoreType: PKCS12
    keyAlias: tomcat-susi
    key-password: Mimojal263!.
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.12.9:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: 192.168.12.9
    securePortEnabled: true
    securePort: ${server.port}
spring:
  redis.host: 192.168.12.9
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000

spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure/
  public.directory: /home/admdevlin/ArchivosFGN/public/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /core/**
      serviceId: core
    pef:
      path: /pef/**
      serviceId: pef
    feab:
      path: /goods/**
      serviceId: goods