security:
  sessions: ALWAYS
server:
  port: 8082
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.12.9:8761/eureka/
  instance:
    preferIpAddress: false
spring.redis.host: 192.168.12.9
logging.level.: WARN
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000
gateway:
  ribbon:
    listOfServers: localhost:8082

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: core
    security:
      path: /security/**
      serviceId: core
    pef:
      path: /pef/**
      serviceId: pef
    feab:
      path: /goods/**
      serviceId: goods