spring.redis.host: 192.168.0.9
security:
  sessions: ALWAYS
spring.profiles: DEVELOPMENT
fgn.loginUrl: http://localhost:8081/PortalFGN/ws-fgn/userByDoc
server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
zuul:
  routes:
    ui:
      url: http://localhost:8083
    fgn-pqrs:
      url: http://localhost:8084
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SECURE_DOC
    password: SECURE_DOC
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: init-data.sql
    show-sql: true
spring.profiles: PRODUCTION
fgn.loginUrl: http://10.1.6.28:8080/PortalFGN/ws-fgn/userByDoc
server:
  port: 8082
logging:
  level:
    org.springframework.security: ERROR
    org.springframework.beans: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
zuul:
  routes:
    ui:
      url: http://localhost:8083
    pqrs:
      url: http://localhost:8084
    user:
      path: /user/**
      url: http://localhost:9999/sso/user
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SECURE_DOC
    password: SECURE_DOC
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: init-data.sql
    show-sql: true