security:
  sessions: ALWAYS
server:
  port: 8082
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    preferIpAddress: true
spring.redis.host: localhost
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SUSI_CORE
    password: '{cipher}77773399b5878b5eebbfac49d96f10c819cd2f592d38793c8d7044853bc7d910'
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true

hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000
gateway:
  ribbon:
    listOfServers: localhost:8082

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: core
    security:
      path: /security/**
      serviceId: core
    pef:
      path: /pef/**
      serviceId: pef
    feab:
      path: /goods/**
      serviceId: goods
