security:
  sessions: ALWAYS
server:
  port: 8082
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@azdevlinfgn2.cloudapp.net:8761/eureka/
  instance:
    preferIpAddress: false
spring.redis.host: localhost
#logging.level.: 'WARN'
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000
gateway:
  ribbon:
    listOfServers: localhost:8082

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    fgn-pqrs:
      url: /pqrs/**
      serviceId: pqrs
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: common
    security:
      path: /security/**
      serviceId: security
    pef:
      path: /pef/**
      serviceId: pef
