security:
  sessions: ALWAYS
server:
  port: 8082
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
#    preferIpAddress: true
    hostname: localhost
spring.redis.host: localhost
logging.level.: WARN
#logging:
#  level:
#    org.springframework.security: WARN
#    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000
gateway:
  ribbon:
    listOfServers: localhost:8082

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: core
    security:
      path: /security/**
      serviceId: core
    pef:
      path: /pef/**
      serviceId: pef
    feab:
      path: /goods/**
      serviceId: goods