security:
  sessions: ALWAYS
server:
  port: 8082
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    hostname: localhost
spring.redis.host: localhost
#logging.level.: 'WARN'
logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true
zuul:
  routes:
    fgn-pqrs:
      url: /pqrs/**
      serviceId: pqrs
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: common
    security:
      path: /security/**
      serviceId: security
    pef:
      path: /pef/**
      serviceId: pef
