security:
  sessions: ALWAYS
server:
  port: 8082
  context-path: /portal
  ssl:
    enabled: true
    key-store: keystore-susi.p12
    key-store-password: Mimojal263!.
    keyStoreType: PKCS12
    keyAlias: tomcat-susi
    key-password: Mimojal263!.
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
#    preferIpAddress: true
    hostname: localhost


#eureka:
#  instance:
#    secureVirtualHostName: ${spring.application.name}
#    hostname: localhost
#    securePort: ${server.port}
#    securePortEnabled: true  
#    nonSecurePortEnabled: false 
#    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: https://localhost:8761/eureka/
      
spring.redis.host: localhost
logging.level.: WARN
#logging:
#  level:
#    org.springframework.security: WARN
#    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SUSI_CORE
    password: '{cipher}77773399b5878b5eebbfac49d96f10c819cd2f592d38793c8d7044853bc7d910'
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: false
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  12000
  IsSecure: true
gateway:
  ribbon:
    listOfServers: localhost:8082
spring.files:
  private.directory: D:/ArchivosFGN/secure/
  public.directory: D:/ArchivosFGN/public/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 12000
  routes:
    frontend:
      path: /ui/**
      serviceId: frontend
    common:
      path: /common/**
      serviceId: core
    security:
      path: /security/**
      serviceId: core
    pef:
      path: /pef/**
      serviceId: pef
    feab:
      path: /goods/**
      serviceId: goods