security.sessions: NEVER
server:
  port: 8086
spring.redis.host: localhost
logging.level.: 'ERROR'
#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
#    properties.hibernate.hbm2ddl.import_files: pef-init-data.sql
    show-sql: false
eureka:
  instance:
    hostname: localhost
spring.files:
  private.directory: D:/ArchivosFGN/secure/
  public.directory: D:/ArchivosFGN/public/
  pef.datasheets.directory: pef/datasheets/
constants.max.pef_data_sheet: 50

hystrix:
  command.default.execution.isolation:
#    semaphore.maxConcurrentRequests: 400
    thread.timeoutInMilliseconds: 20000
    strategy: THREAD
#  threadpool.default.coreSize: 400
  
ribbon:
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  ReadTimeout:  20000
gateway:
  ribbon:
    listOfServers: localhost:8082