security:
  sessions: NEVER
server:
  port: 8086
spring.redis.host: localhost
logging.level.: 'ERROR'
#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure
  public.directory: /home/admdevlin/ArchivosFGN/public
  pef.datasheets.directory: /pef/datasheets
constants.max.pef_data_sheet: 50