security:
  sessions: NEVER
server:
  port: 8086
spring.redis.host: 192.168.12.9
logging.level.: 'ERROR'
#logging:
#  level:
#   org.springframework.security: TRACE
#    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.12.7:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: 192.168.12.9
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure/
  public.directory: /home/admdevlin/ArchivosFGN/public/
  pef.datasheets.directory: pef/datasheets/
constants.max.pef_data_sheet: 50
hystrix:
  command.default.execution.isolation:
    thread.timeoutInMilliseconds: 12000
    strategy: THREAD