security:
  sessions: NEVER
server:
  port: 8086
eureka:
  password: '123456'
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
#    preferIpAddress: true
spring.redis.host: localhost
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: WARN
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: pef-init-data.sql
    show-sql: true
spring.files:
  private.directory: D:/ArchivosFGN/secure
  public.directory: D:/ArchivosFGN/public
  pef.datasheets.directory: /pef/datasheets
constants.max.pef_data_sheet: 50