security:
  sessions: NEVER
server:
  port: 8081
spring.redis.host: localhost
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true
spring.files:
  private.directory: D:/ArchivosFGN/secure
  public.directory: D:/ArchivosFGN/public