security:
  sessions: NEVER
server:
  port: 8081
spring.redis.host: localhost
eureka:
  instance:
    hostname: localhost
logging:
  level.: INFO
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FGN_2015
    password: FGN_2015
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.import_files: init-data.sql
    show-sql: true
spring.files:
  private.directory: /home/admdevlin/ArchivosFGN/secure
  public.directory: /home/admdevlin/ArchivosFGN/public
ldap:
  contextSource:
    url: ldap://40.118.255.23:389
    userDn: FISCALIATEST\usuarioadpruebas
    password: AdmAdPrueba2014
    base: DC=fiscalia,DC=test
#    clean: true
    directory.type: NORMAL